student_count = 11
#prints list of students
puts "The students of Villans Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alec DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krugar"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"
puts "Overall, we have #{student_count} great students"